/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.imagecolor;

import java.awt.event.ItemEvent;

/**
 *
 * @author eduma
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        labelAviso.setVisible(false);
        radioSupDerecha.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioGroup = new javax.swing.ButtonGroup();
        lienzo1 = new com.mycompany.imagecolor.Lienzo();
        panelColores = new javax.swing.JPanel();
        checkBoxAll = new javax.swing.JCheckBox();
        checkBoxRojo = new javax.swing.JCheckBox();
        checkBoxAzul = new javax.swing.JCheckBox();
        checkBoxVerde = new javax.swing.JCheckBox();
        labelColores = new javax.swing.JLabel();
        panelRadio = new javax.swing.JPanel();
        radioSupDerecha = new javax.swing.JRadioButton();
        radioSupIzquierda = new javax.swing.JRadioButton();
        radioInfDer = new javax.swing.JRadioButton();
        radioInfIzq = new javax.swing.JRadioButton();
        labelLogo = new javax.swing.JLabel();
        panelAviso = new javax.swing.JPanel();
        labelAviso = new javax.swing.JLabel();
        labelCopyFer = new javax.swing.JLabel();
        labelCopyEdu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lienzo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout lienzo1Layout = new javax.swing.GroupLayout(lienzo1);
        lienzo1.setLayout(lienzo1Layout);
        lienzo1Layout.setHorizontalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        lienzo1Layout.setVerticalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );

        panelColores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        checkBoxAll.setSelected(true);
        checkBoxAll.setText("Todos");
        checkBoxAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxAllActionPerformed(evt);
            }
        });

        checkBoxRojo.setSelected(true);
        checkBoxRojo.setText("Rojo");
        checkBoxRojo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkBoxRojoItemStateChanged(evt);
            }
        });

        checkBoxAzul.setSelected(true);
        checkBoxAzul.setText("Azul");
        checkBoxAzul.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkBoxAzulItemStateChanged(evt);
            }
        });

        checkBoxVerde.setSelected(true);
        checkBoxVerde.setText("Verde");
        checkBoxVerde.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkBoxVerdeItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panelColoresLayout = new javax.swing.GroupLayout(panelColores);
        panelColores.setLayout(panelColoresLayout);
        panelColoresLayout.setHorizontalGroup(
            panelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelColoresLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(panelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkBoxVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxRojo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxAll, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        panelColoresLayout.setVerticalGroup(
            panelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelColoresLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(checkBoxAll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxRojo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxVerde)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        labelColores.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelColores.setText("Canales de colores");

        panelRadio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        radioGroup.add(radioSupDerecha);
        radioSupDerecha.setText("Superior derecha");
        radioSupDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSupDerechaActionPerformed(evt);
            }
        });

        radioGroup.add(radioSupIzquierda);
        radioSupIzquierda.setText("Superior izquierda");
        radioSupIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSupIzquierdaActionPerformed(evt);
            }
        });

        radioGroup.add(radioInfDer);
        radioInfDer.setText("Inferior derecha");
        radioInfDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioInfDerActionPerformed(evt);
            }
        });

        radioGroup.add(radioInfIzq);
        radioInfIzq.setText("Inferior izquierda");
        radioInfIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioInfIzqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRadioLayout = new javax.swing.GroupLayout(panelRadio);
        panelRadio.setLayout(panelRadioLayout);
        panelRadioLayout.setHorizontalGroup(
            panelRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRadioLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(radioSupDerecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioSupIzquierda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioInfDer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioInfIzq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panelRadioLayout.setVerticalGroup(
            panelRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRadioLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(radioSupDerecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioSupIzquierda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioInfDer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radioInfIzq))
        );

        labelLogo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelLogo.setText("Marca de agua");

        labelAviso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelAviso.setText("Al menos un canal de color debe esta activo");

        javax.swing.GroupLayout panelAvisoLayout = new javax.swing.GroupLayout(panelAviso);
        panelAviso.setLayout(panelAvisoLayout);
        panelAvisoLayout.setHorizontalGroup(
            panelAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAvisoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelAvisoLayout.setVerticalGroup(
            panelAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAvisoLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(labelAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        labelCopyFer.setText("© Fernando Marcelo Alonso");

        labelCopyEdu.setText(" Eduardo Maldonado Fernández");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lienzo1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(59, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(panelColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panelAviso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(panelRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12))
                                    .addComponent(labelCopyFer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(114, 114, 114))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labelCopyEdu, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(labelColores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelLogo)
                .addGap(150, 150, 150))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lienzo1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelColores)
                    .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelCopyFer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelCopyEdu))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelAviso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkBoxAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxAllActionPerformed
        if(checkBoxAll.isSelected()){
            checkBoxRojo.setSelected(true);
            checkBoxVerde.setSelected(true);
            checkBoxAzul.setSelected(true);
        }
    }//GEN-LAST:event_checkBoxAllActionPerformed

    private void radioSupDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSupDerechaActionPerformed
        lienzo1.setPositionLogo(510,-50);
    }//GEN-LAST:event_radioSupDerechaActionPerformed

    private void radioSupIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSupIzquierdaActionPerformed
        lienzo1.setPositionLogo(0,-50);

    }//GEN-LAST:event_radioSupIzquierdaActionPerformed

    private void radioInfDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioInfDerActionPerformed
        lienzo1.setPositionLogo(510,330);
    }//GEN-LAST:event_radioInfDerActionPerformed

    private void radioInfIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioInfIzqActionPerformed
        lienzo1.setPositionLogo(0,330);
    }//GEN-LAST:event_radioInfIzqActionPerformed

    private void checkBoxRojoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkBoxRojoItemStateChanged
        disableAll();
        if(countTrue(getActiveColor()) == 0){
            checkBoxRojo.setSelected(true);
        }else if(countTrue(getActiveColor()) == 1){
            labelAviso.setVisible(true);
            lienzo1.checkBoxChange(checkBoxRojo.isSelected(), checkBoxVerde.isSelected(), checkBoxAzul.isSelected());
        }else{
            labelAviso.setVisible(false);
            lienzo1.checkBoxChange(checkBoxRojo.isSelected(), checkBoxVerde.isSelected(), checkBoxAzul.isSelected());
        }
    }//GEN-LAST:event_checkBoxRojoItemStateChanged

    private void checkBoxVerdeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkBoxVerdeItemStateChanged
        disableAll();
        if(countTrue(getActiveColor()) == 0){
            checkBoxVerde.setSelected(true);
            labelAviso.setVisible(true);
        }else if(countTrue(getActiveColor()) == 1){
            labelAviso.setVisible(true);
            lienzo1.checkBoxChange(checkBoxRojo.isSelected(), checkBoxVerde.isSelected(), checkBoxAzul.isSelected());
        }else{
            lienzo1.checkBoxChange(checkBoxRojo.isSelected(), checkBoxVerde.isSelected(), checkBoxAzul.isSelected());
            labelAviso.setVisible(false);
        }
    }//GEN-LAST:event_checkBoxVerdeItemStateChanged

    private void checkBoxAzulItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkBoxAzulItemStateChanged
        disableAll();
        if(countTrue(getActiveColor()) == 0){
            checkBoxAzul.setSelected(true);
            labelAviso.setVisible(true);
        }else if(countTrue(getActiveColor()) == 1){
            labelAviso.setVisible(true);
            lienzo1.checkBoxChange(checkBoxRojo.isSelected(), checkBoxVerde.isSelected(), checkBoxAzul.isSelected());
        }else{
            lienzo1.checkBoxChange(checkBoxRojo.isSelected(), checkBoxVerde.isSelected(), checkBoxAzul.isSelected());
            labelAviso.setVisible(false);
        }
    }//GEN-LAST:event_checkBoxAzulItemStateChanged

    private boolean [] getActiveColor(){
        return new boolean [] {checkBoxRojo.isSelected(), checkBoxVerde.isSelected(), checkBoxAzul.isSelected()};
    }
    
    private int countTrue(boolean [] actColor){
        int count = 0;
        for (int i = 0; i < actColor.length; i++){
            if (actColor[i]){
                count++;
            }
        }
        return count;
    }
    
    private void disableAll(){
        if(countTrue(getActiveColor()) == 2){
            checkBoxAll.setSelected(false);
        }
        if(countTrue(getActiveColor()) == 3){
            checkBoxAll.setSelected(true);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkBoxAll;
    private javax.swing.JCheckBox checkBoxAzul;
    private javax.swing.JCheckBox checkBoxRojo;
    private javax.swing.JCheckBox checkBoxVerde;
    private javax.swing.JLabel labelAviso;
    private javax.swing.JLabel labelColores;
    private javax.swing.JLabel labelCopyEdu;
    private javax.swing.JLabel labelCopyFer;
    private javax.swing.JLabel labelLogo;
    private com.mycompany.imagecolor.Lienzo lienzo1;
    private javax.swing.JPanel panelAviso;
    private javax.swing.JPanel panelColores;
    private javax.swing.JPanel panelRadio;
    private javax.swing.ButtonGroup radioGroup;
    private javax.swing.JRadioButton radioInfDer;
    private javax.swing.JRadioButton radioInfIzq;
    private javax.swing.JRadioButton radioSupDerecha;
    private javax.swing.JRadioButton radioSupIzquierda;
    // End of variables declaration//GEN-END:variables
}
